# Generated by Django 5.2.2 on 2025-10-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_medicalreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalreport",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
