# Generated by Django 5.2.2 on 2025-06-13 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(default='Dentist', max_length=100)),
                ('license_number', models.CharField(max_length=50)),
                ('clinic_name', models.CharField(default='Dental Clinic', max_length=255)),
                ('clinic_address', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('available', 'Available'), ('unavailable', 'Unavailable')], max_length=11, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
    ]
