# Generated by Django 5.2.2 on 2025-06-13 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='profile',
        ),
    ]
