# Generated by Django 5.2.2 on 2025-06-20 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_appointment_appointment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_service', to='patients.service'),
        ),
    ]
