# Generated by Django 5.2.2 on 2025-06-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_alter_subservice_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, choices=[('confirm', 'Confirm'), ('pending', 'Pending'), ('completed', 'Completed'), ('no-show', 'No-Show')], default='pending', max_length=10, null=True),
        ),
    ]
